"""
Tavily Web Search — fetches real current news about a political question.
Includes 24-hour date filtering for fresh news.
"""

import os
from datetime import datetime, timedelta

from vg.config import config

NO_WEB_RESULTS_TEXT = "No web search results available (web search disabled or unavailable)."
NO_WEB_MARKERS = (
    "no web search results available",
    "no relevant news found",
    "tavily not installed",
    "web search failed",
)


def web_search_enabled() -> bool:
    """Return True when Tavily-backed web search should be used."""
    if config.disable_web_search:
        return False
    env_override = os.getenv("VG_DISABLE_WEB_SEARCH", "").lower()
    if env_override in {"1", "true", "yes", "on"}:
        return False
    return True


def has_real_news_content(text: str) -> bool:
    """Centralized check for whether web search returned real evidence."""
    cleaned = (text or "").strip().lower()
    if not cleaned:
        return False
    return not any(marker in cleaned for marker in NO_WEB_MARKERS)


def search_news(query: str, max_results: int = 4) -> str:
    """Search for current news using Tavily API with 24-hour date filtering."""
    if not web_search_enabled():
        print("  ⚠ Web search disabled — skipping Tavily")
        return NO_WEB_RESULTS_TEXT

    api_key = os.getenv("TAVILY_API_KEY") or config.tavily_api_key
    if not api_key:
        print("  ⚠ TAVILY_API_KEY not set — skipping web search")
        return NO_WEB_RESULTS_TEXT

    # Calculate date range for last 24 hours
    now = datetime.utcnow()
    yesterday = now - timedelta(hours=24)
    date_from = yesterday.strftime("%Y-%m-%d")

    try:
        from tavily import TavilyClient
        client = TavilyClient(api_key=api_key)

        # Enhanced query with date filter
        enhanced_query = f"{query} latest news"
        
        response = client.search(
            query=enhanced_query,
            search_depth="basic",
            max_results=max_results,
            include_answer=True,
            # Filter by date (Tavily supports this via API parameters)
            from_date=date_from,
        )

        parts = []

        # Add timestamp header
        parts.append(f"📰 LIVE NEWS — Last 24 Hours ({date_from} to {now.strftime('%Y-%m-%d')})")
        parts.append("")

        # Tavily's AI-generated answer summary
        if response.get("answer"):
            parts.append(f"SUMMARY: {response['answer']}")

        # Individual results
        for i, result in enumerate(response.get("results", [])[:max_results], 1):
            title = result.get("title", "No title")
            content = result.get("content", "")[:220]
            url = result.get("url", "")
            parts.append(f"\n[{i}] {title}\n    {content}\n    Source: {url}")

        return "\n".join(parts) if parts else NO_WEB_RESULTS_TEXT

    except ImportError:
        return "Tavily not installed. Run: pip install tavily-python"
    except Exception as e:
        # Fallback: try without date filter
        try:
            from tavily import TavilyClient
            client = TavilyClient(api_key=api_key)
            response = client.search(
                query=query,
                search_depth="basic",
                max_results=max_results,
                include_answer=True,
            )
            parts = ["📰 LIVE NEWS (fallback mode)"]
            if response.get("answer"):
                parts.append(f"SUMMARY: {response['answer']}")
            for i, result in enumerate(response.get("results", [])[:max_results], 1):
                title = result.get("title", "No title")
                content = result.get("content", "")[:220]
                url = result.get("url", "")
                parts.append(f"\n[{i}] {title}\n    {content}\n    Source: {url}")
            return "\n".join(parts)
        except Exception as fallback_error:
            print(f"  ⚠ Tavily search error: {e}")
            return f"Web search failed: {fallback_error}"


def search_contrarian(queries: list[str], max_results_per_query: int = 2) -> str:
    """
    Oracle Mode contrarian search — fetches OPPOSING viewpoints and ground-level reports.

    Unlike search_news() which finds mainstream consensus, this function
    searches for evidence that the consensus could be wrong.

    Args:
        queries: List of contrarian search queries (generated by ContrarianSearchGenerator)
        max_results_per_query: Max results per query (keep low to avoid token bloat)

    Returns:
        Combined contrarian evidence text
    """
    if not web_search_enabled():
        return ""

    api_key = os.getenv("TAVILY_API_KEY") or config.tavily_api_key
    if not api_key:
        return ""

    try:
        from tavily import TavilyClient
        client = TavilyClient(api_key=api_key)
    except ImportError:
        return ""

    all_parts = ["🔮 ORACLE MODE — CONTRARIAN EVIDENCE SEARCH", ""]
    results_found = 0

    for i, query in enumerate(queries[:3], 1):  # Max 3 queries to control costs
        try:
            response = client.search(
                query=query,
                search_depth="basic",
                max_results=max_results_per_query,
                include_answer=True,
            )

            query_parts = [f"[Contrarian Query {i}] \"{query}\""]

            if response.get("answer"):
                query_parts.append(f"  Summary: {response['answer'][:200]}")

            for result in response.get("results", [])[:max_results_per_query]:
                title = result.get("title", "No title")
                content = result.get("content", "")[:180]
                query_parts.append(f"  • {title}: {content}")
                results_found += 1

            all_parts.extend(query_parts)
            all_parts.append("")

        except Exception as e:
            all_parts.append(f"[Contrarian Query {i}] Failed: {e}")

    if results_found == 0:
        return ""

    return "\n".join(all_parts)
